# Generated by Django 5.1.2 on 2025-05-11 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('assembling', 'В сборке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], default='pending', max_length=20),
        ),
    ]
