# Generated by Django 5.2.1 on 2025-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pcbuild_created_at_pcbuild_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
